name: Deploy game to PA

on:
  # push:
  #   branches: [ 'main' ]
  workflow_dispatch:

env:
  # target 
  HOST: ssh.pythonanywhere.com
  USER: snakesandladders
  # global options
  SSH_OPTIONS: -i ~/.ssh/id_rsa_snakes -o LogLevel=ERROR -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  

jobs:
  deploy_game_to_pa:
    runs-on: ubuntu-latest
    steps:
    - name: Get deployment files
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ID_RSA_SNAKES }}
        name: id_rsa_snakes
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Check OS and node version
      run: |
        echo $ pwd
        pwd

    - name: Run a command on the remote
      run: |
        export TARGET=$USER@$HOST
        export RUN="ssh $SSH_OPTIONS $TARGET"
        echo $ hi!
        $RUN ls -la
        $RUN 'cd ~/projects/summer-project; git pull'