name: Say hello

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:
  
jobs: 
  say_hello:  
    runs-on: ubuntu-latest
    steps:
      - name: Get deployment files
        uses: actions/checkout@v2
      - name: Run some example commands
        run: |
          echo $ echo Hello!
          echo Hello!
          echo $ pwd
          pwd
          echo $ ls -la
          ls -la
          echo $ python --version
          python --version
          echo $ node --version
          node --version
      - name: Run some example commands
        run: |
          echo $ python hello.py
          python hello.py
